name: Deploy Vite to Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # 删掉 cache: 'npm'，不再读取lock文件

      - name: Install dependencies
        run: npm install

      - name: Run Vite Build
        run: npm run build

      - name: Check dist folder
        run: |
          ls -la
          if [ -d "dist" ]; then
            echo "✅ dist文件夹存在"
            ls -la dist
          else
            echo "❌ dist文件夹不存在，打包失败！"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
